/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro.notification.publish;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NotificationType {
  error, warning, information, unclassified  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationType\",\"namespace\":\"example.avro.notification.publish\",\"symbols\":[\"error\",\"warning\",\"information\",\"unclassified\"],\"default\":\"unclassified\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
