/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro.sparkpoc;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Outcome {
  Delivered, Returned  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Outcome\",\"namespace\":\"example.avro.sparkpoc\",\"symbols\":[\"Delivered\",\"Returned\"],\"default\":\"Delivered\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
